#!/bin/sh
sed -i '' 's/ACACH/PASSERIFORMES_Acanthisittidae_Acanthisitta_chloris/g' $1
sed -i '' 's/ANAPL/ANSERIFORMES_Anatidae_Anas_platyrhynchos/g' $1
sed -i '' 's/CAPCA/CAPRIMULGIFORMES_Caprimulgidae_Antrostomus_carolinensis/g' $1
sed -i '' 's/APAVI/TROGONIFORMES_Trogonidae_Apaloderma_vittatum/g' $1
sed -i '' 's/APTFO/SPHENISCIFORMES_Spheniscidae_Aptenodytes_forsteri/g' $1
sed -i '' 's/BALRE/GRUIFORMES_Gruidae_Balearica_regulorum/g' $1
sed -i '' 's/BUCRH/BUCEROTIFORMES_Bucerotidae_Buceros_rhinoceros/g' $1
sed -i '' 's/CALAN/APODIFORMES_Trochilidae_Calypte_anna/g' $1
sed -i '' 's/CARCR/CARIAMIFORMES_Cariamidae_Cariama_cristata/g' $1
sed -i '' 's/CATAU/ACCIPITRIFORMES_Cathartidae_Cathartes_aura/g' $1
sed -i '' 's/CHAPE/APODIFORMES_Apodidae_Chaetura_pelagica/g' $1
sed -i '' 's/CHAVO/CHARADRIIFORMES_Charadriidae_Charadrius_vociferus/g' $1
sed -i '' 's/CHLUN/OTIDIFORMES_Otididae_Chlamydotis_macqueenii/g' $1
sed -i '' 's/COLST/COLIIFORMES_Coliidae_Colius_striatus/g' $1
sed -i '' 's/COLLI/COLUMBIFORMES_Columbidae_Columba_livia/g' $1
sed -i '' 's/CORBR/PASSERIFORMES_Corvidae_Corvus_brachyrhynchos/g' $1
sed -i '' 's/CUCCA/CUCULIFORMES_Cuculidae_Cuculus_canorus/g' $1
sed -i '' 's/PICPU/PICIFORMES_Picidae_Dryobates_pubescens/g' $1
sed -i '' 's/EGRGA/PELECANIFORMES_Ardeidae_Egretta_garzetta/g' $1
sed -i '' 's/EURHE/EURYPYGIFORMES_Eurypygidae_Eurypyga_helias/g' $1
sed -i '' 's/FALPE/FALCONIFORMES_Falconidae_Falco_peregrinus/g' $1
sed -i '' 's/FULGL/PROCELLARIIFORMES_Procellariidae_Fulmarus_glacialis/g' $1
sed -i '' 's/GALGA/GALLIFORMES_Phasianidae_Gallus_gallus/g' $1
sed -i '' 's/GAVST/GAVIIFORMES_Gaviidae_Gavia_stellata/g' $1
sed -i '' 's/GEOFO/PASSERIFORMES_Thraupidae_Geospiza_fortis/g' $1
sed -i '' 's/HALAL/ACCIPITRIFORMES_Accipitridae_Haliaeetus_albicilla/g' $1
sed -i '' 's/HALLE/ACCIPITRIFORMES_Accipitridae_Haliaeetus_leucocephalus/g' $1
sed -i '' 's/LEPDI/LEPTOSOMIFORMES_Leptosomidae_Leptosomus_discolor/g' $1
sed -i '' 's/MANVI/PASSERIFORMES_Pipridae_Manacus_vitellinus/g' $1
sed -i '' 's/MELGA/GALLIFORMES_Phasianidae_Meleagris_gallopavo/g' $1
sed -i '' 's/MELUN/PSITTACIFORMES_Psittaculidae_Melopsittacus_undulatus/g' $1
sed -i '' 's/MERNU/CORACIIFORMES_Meropidae_Merops_nubicus/g' $1
sed -i '' 's/MESUN/MESITORNITHIFORMES_Mesitornithidae_Mesitornis_unicolor/g' $1
sed -i '' 's/NESNO/PSITTACIFORMES_Strigopidae_Nestor_notabilis/g' $1
sed -i '' 's/NIPNI/PELECANIFORMES_Threskiornithidae_Nipponia_nippon/g' $1
sed -i '' 's/OPHHO/OPISTHOCOMIFORMES_Opisthocomidae_Opisthocomus_hoazin/g' $1
sed -i '' 's/PELCR/PELECANIFORMES_Pelecanidae_Pelecanus_crispus/g' $1
sed -i '' 's/PHALE/PHAETHONTIFORMES_Phaethontidae_Phaethon_lepturus/g' $1
sed -i '' 's/PHACA/SULIFORMES_Phalacrocoracidae_Phalacrocorax_carbo/g' $1
sed -i '' 's/PHORU/PHOENICOPTERIFORMES_Phoenicopteridae_Phoenicopterus_ruber/g' $1
sed -i '' 's/PODCR/PODICIPEDIFORMES_Podicipedidae_Podiceps_cristatus/g' $1
sed -i '' 's/PTEGU/PTEROCLIFORMES_Pteroclidae_Pterocles_gutturalis/g' $1
sed -i '' 's/PYGAD/SPHENISCIFORMES_Spheniscidae_Pygoscelis_adeliae/g' $1
sed -i '' 's/STRCA/STRUTHIONIFORMES_Struthionidae_Struthio_camelus/g' $1
sed -i '' 's/TAEGU/PASSERIFORMES_Estrildidae_Taeniopygia_guttata/g' $1
sed -i '' 's/TAUER/MUSOPHAGIFORMES_Musophagidae_Tauraco_erythrolophus/g' $1
sed -i '' 's/TINMA/TINAMIFORMES_Tinamidae_Tinamus_guttatus/g' $1
sed -i '' 's/TYTAL/STRIGIFORMES_Tytonidae_Tyto_alba/g' $1
