#!/bin/sh
sed -i '' 's/abroscopus_albogularis_28164/PASSERIFORMES_Cettiidae_Abroscopus_albogularis/g' $1
sed -i '' 's/acanthisitta_chloris/PASSERIFORMES_Acanthisittidae_Acanthisitta_chloris/g' $1
sed -i '' 's/acanthiza_cinerea_18352/PASSERIFORMES_Acanthizidae_Acanthiza_cinerea/g' $1
sed -i '' 's/acanthorhynchus_tenuirostris_10667/PASSERIFORMES_Meliphagidae_Acanthorhynchus_tenuirostris/g' $1
sed -i '' 's/acrocephalus_orientalis_28793/PASSERIFORMES_Acrocephalidae_Acrocephalus_orientalis/g' $1
sed -i '' 's/aegithalos_concinnus_28044/PASSERIFORMES_Aegithalidae_Aegithalos_concinnus/g' $1
sed -i '' 's/aegithina_lafresnayei_23213/PASSERIFORMES_Aegithinidae_Aegithina_lafresnayei/g' $1
sed -i '' 's/aegotheles_cristatus/AEGOTHELIFORMES_Aegothelidae_Aegotheles_cristatus/g' $1
sed -i '' 's/aegotheles_insignis/AEGOTHELIFORMES_Aegothelidae_Aegotheles_insignis/g' $1
sed -i '' 's/aerodramus_vanikorensis2/APODIFORMES_Apodidae_Aerodramus_vanikorensis/g' $1
sed -i '' 's/ailuroedus_buccoides_12226/PASSERIFORMES_Ptilonorhynchidae_Ailuroedus_buccoides/g' $1
sed -i '' 's/ajaia_ajaja/PELECANIFORMES_Threskiornithidae_Platalea_ajaja/g' $1
sed -i '' 's/alca_torda_b77512/CHARADRIIFORMES_Alcidae_Alca_torda/g' $1
sed -i '' 's/alcedo_leucogaster/CORACIIFORMES_Alcedinidae_Corythornis_leucogaster/g' $1
sed -i '' 's/alectura_lathami2/GALLIFORMES_Megapodiidae_Alectura_lathami/g' $1
sed -i '' 's/alligator_mississippiensis/OUTGROUP_Alligatoridae_Alligator_mississippiensis/g' $1
sed -i '' 's/amazona_autumnalis/PSITTACIFORMES_Psittacidae_Amazona_autumnalis/g' $1
sed -i '' 's/ammodramus_savannarum_b8557/PASSERIFORMES_Passerellidae_Ammodramus_savannarum/g' $1
sed -i '' 's/anas_platyrhynchos/ANSERIFORMES_Anatidae_Anas_platyrhynchos/g' $1
sed -i '' 's/anhinga_anhinga/SULIFORMES_Anhingidae_Anhinga_anhinga/g' $1
sed -i '' 's/anser_erythropus/ANSERIFORMES_Anatidae_Anser_erythropus/g' $1
sed -i '' 's/anseranas_semipalmata/ANSERIFORMES_Anseranatidae_Anseranas_semipalmata/g' $1
sed -i '' 's/apalharpactes_mackloti_b49104/TROGONIFORMES_Trogonidae_Apalharpactes_mackloti/g' $1
sed -i '' 's/apaloderma_narina/TROGONIFORMES_Trogonidae_Apaloderma_narina/g' $1
sed -i '' 's/aptenodytes_patagonicus/SPHENISCIFORMES_Spheniscidae_Aptenodytes_patagonicus/g' $1
sed -i '' 's/apteryx_australis/APTERYGIFORMES_Apterygidae_Apteryx_australis/g' $1
sed -i '' 's/aramus_guarauna/GRUIFORMES_Aramidae_Aramus_guarauna/g' $1
sed -i '' 's/ardea_herodias/PELECANIFORMES_Ardeidae_Ardea_herodias/g' $1
sed -i '' 's/ardeotis_kori/OTIDIFORMES_Otididae_Ardeotis_kori/g' $1
sed -i '' 's/arenaria_interpres/CHARADRIIFORMES_Scolopacidae_Arenaria_interpres/g' $1
sed -i '' 's/artamus_cinereus_6183/PASSERIFORMES_Artamidae_Artamus_cinereus/g' $1
sed -i '' 's/atrichornis_rufescens_554508/PASSERIFORMES_Atrichornithidae_Atrichornis_rufescens/g' $1
sed -i '' 's/batrachostomus_septimus3/PODARGIFORMES_Podargidae_Batrachostomus_septimus/g' $1
sed -i '' 's/belaeniceps_rex/PELECANIFORMES_Balaenicipitidae_Balaeniceps_rex/g' $1
sed -i '' 's/biziura_lobata/ANSERIFORMES_Anatidae_Biziura_lobata/g' $1
sed -i '' 's/bleda_syndactylus_29008/PASSERIFORMES_Pycnonotidae_Bleda_syndactylus/g' $1
sed -i '' 's/bombycilla_garrulus_21744/PASSERIFORMES_Bombycillidae_Bombycilla_garrulus/g' $1
sed -i '' 's/brachygalba_albogularus/PICIFORMES_Galbulidae_Brachygalba_albogularis/g' $1
sed -i '' 's/brachypteracias_squamigera/CORACIIFORMES_Brachypteraciidae_Geobiastes_squamiger/g' $1
sed -i '' 's/bucco_macrodactylus/PICIFORMES_Bucconidae_Bucco_macrodactylus/g' $1
sed -i '' 's/buceros_rhinoceros2/BUCEROTIFORMES_Bucerotidae_Buceros_rhinoceros/g' $1
sed -i '' 's/bucorvus_abyssinicus/BUCEROTIFORMES_Bucorvidae_Bucorvus_abyssinicus/g' $1
sed -i '' 's/buphagus_erythrorhynchus_26687/PASSERIFORMES_Buphagidae_Buphagus_erythrorynchus/g' $1
sed -i '' 's/burhinus_bistriatus2/CHARADRIIFORMES_Burhinidae_Burhinus_bistriatus/g' $1
sed -i '' 's/buteo_jamaicensis/ACCIPITRIFORMES_Accipitridae_Buteo_jamaicensis/g' $1
sed -i '' 's/cacatua_sulphurea/PSITTACIFORMES_Cacatuidae_Cacatua_sulphurea/g' $1
sed -i '' 's/calcarius_lapponicus_b46289/PASSERIFORMES_Calcariidae_Calcarius_lapponicus/g' $1
sed -i '' 's/calyptomena_viridis_b36377/PASSERIFORMES_Calyptomenidae_Calyptomena_viridis/g' $1
sed -i '' 's/calyptophilus_tertius_8060/PASSERIFORMES_Calyptophilidae_Calyptophilus_tertius/g' $1
sed -i '' 's/capito_niger/PICIFORMES_Capitonidae_Capito_niger/g' $1
sed -i '' 's/caprimulgus_longirostris2/CAPRIMULGIFORMES_Caprimulgidae_Systellura_longirostris/g' $1
sed -i '' 's/caracara_cheriway_b5328/FALCONIFORMES_Falconidae_Caracara_plancus/g' $1
sed -i '' 's/cardinalis_cardinalis_25393/PASSERIFORMES_Cardinalidae_Cardinalis_cardinalis/g' $1
sed -i '' 's/cariama_cristata/CARIAMIFORMES_Cariamidae_Cariama_cristata/g' $1
sed -i '' 's/casuarius_casuarius/CASUARIIFORMES_Casuariidae_Casuarius_casuarius/g' $1
sed -i '' 's/cathartes_aura/ACCIPITRIFORMES_Cathartidae_Cathartes_aura/g' $1
sed -i '' 's/centropus_viridis3/CUCULIFORMES_Cuculidae_Centropus_viridis/g' $1
sed -i '' 's/certhia_americana_30065/PASSERIFORMES_Certhiidae_Certhia_americana/g' $1
sed -i '' 's/chaetops_frenatus_52974/PASSERIFORMES_Chaetopidae_Chaetops_frenatus/g' $1
sed -i '' 's/chalcopsitta_cardinalis/PSITTACIFORMES_Psittaculidae_Pseudeos_cardinalis/g' $1
sed -i '' 's/charadrius_vociferus/CHARADRIIFORMES_Charadriidae_Charadrius_vociferus/g' $1
sed -i '' 's/chauna_torquata/ANSERIFORMES_Anhimidae_Chauna_torquata/g' $1
sed -i '' 's/chelidorhynx_hypoxanthus_28022/PASSERIFORMES_Stenostiridae_Chelidorhynx_hypoxanthus/g' $1
sed -i '' 's/chionis_alba/CHARADRIIFORMES_Chionidae_Chionis_albus/g' $1
sed -i '' 's/chloroceryle_aenea/CORACIIFORMES_Alcedinidae_Chloroceryle_aenea/g' $1
sed -i '' 's/chloropsis_cochinchinensis_b84885/PASSERIFORMES_Chloropseidae_Chloropsis_cochinchinensis/g' $1
sed -i '' 's/chloropsis_sonnerati_24451/PASSERIFORMES_Chloropseidae_Chloropsis_sonnerati/g' $1
sed -i '' 's/cholornis_unicolor_15113/PASSERIFORMES_Paradoxornithidae_Cholornis_unicolor/g' $1
sed -i '' 's/chunga_burmeisteri/CARIAMIFORMES_Cariamidae_Chunga_burmeisteri/g' $1
sed -i '' 's/ciconia_ciconia/CICONIIFORMES_Ciconiidae_Ciconia_ciconia/g' $1
sed -i '' 's/cinclosoma_punctatum_57790/PASSERIFORMES_Cinclosomatidae_Cinclosoma_punctatum/g' $1
sed -i '' 's/cinclus_pallasii_11246/PASSERIFORMES_Cinclidae_Cinclus_pallasii/g' $1
sed -i '' 's/cisticola_anonymus_29165/PASSERIFORMES_Cisticolidae_Cisticola_anonymus/g' $1
sed -i '' 's/climacteris_melanurus_8858/PASSERIFORMES_Climacteridae_Climacteris_melanurus/g' $1
sed -i '' 's/cnemophilus_loriae_16529/PASSERIFORMES_Cnemophilidae_Cnemophilus_loriae/g' $1
sed -i '' 's/coccyzus_americanus/CUCULIFORMES_Cuculidae_Coccyzus_americanus/g' $1
sed -i '' 's/cochlearius_cochlearius2/PELECANIFORMES_Ardeidae_Cochlearius_cochlearius/g' $1
sed -i '' 's/coereba_flaveola_b46656/PASSERIFORMES_Thraupidae_Coereba_flaveola/g' $1
sed -i '' 's/colibri_coruscans/APODIFORMES_Trochilidae_Colibri_coruscans/g' $1
sed -i '' 's/colinus_cristatus/GALLIFORMES_Odontophoridae_Colinus_cristatus/g' $1
sed -i '' 's/colius_colius/COLIIFORMES_Coliidae_Colius_colius/g' $1
sed -i '' 's/colluricincla_harmonica_8866/PASSERIFORMES_Pachycephalidae_Colluricincla_harmonica/g' $1
sed -i '' 's/columba_livia/COLUMBIFORMES_Columbidae_Columba_livia/g' $1
sed -i '' 's/columbina_passerina2/COLUMBIFORMES_Columbidae_Columbina_passerina/g' $1
sed -i '' 's/conopophaga_aurita_b35281/PASSERIFORMES_Conopophagidae_Conopophaga_aurita/g' $1
sed -i '' 's/coracias_caudata2/CORACIIFORMES_Coraciidae_Coracias_caudatus/g' $1
sed -i '' 's/cormobates_leucophaea_57452/PASSERIFORMES_Climacteridae_Cormobates_leucophaea/g' $1
sed -i '' 's/corvus_corax_30042/PASSERIFORMES_Corvidae_Corvus_corax/g' $1
sed -i '' 's/corythaeola_cristata2/MUSOPHAGIFORMES_Musophagidae_Corythaeola_cristata/g' $1
sed -i '' 's/cotinga_nattererii_b28578/PASSERIFORMES_Cotingidae_Cotinga_nattererii/g' $1
sed -i '' 's/coturnix_coturnix/GALLIFORMES_Phasianidae_Coturnix_coturnix/g' $1
sed -i '' 's/coua_cristata/CUCULIFORMES_Cuculidae_Coua_cristata/g' $1
sed -i '' 's/crax_alector/GALLIFORMES_Cracidae_Crax_alector/g' $1
sed -i '' 's/crinifer_piscator/MUSOPHAGIFORMES_Musophagidae_Crinifer_piscator/g' $1
sed -i '' 's/crotophaga_sulcirostris/CUCULIFORMES_Cuculidae_Crotophaga_sulcirostris/g' $1
sed -i '' 's/crypturellus_soui/TINAMIFORMES_Tinamidae_Crypturellus_soui/g' $1
sed -i '' 's/cuculus_canorus/CUCULIFORMES_Cuculidae_Cuculus_canorus/g' $1
sed -i '' 's/culicicapa_ceylonensis_9948/PASSERIFORMES_Stenostiridae_Culicicapa_ceylonensis/g' $1
sed -i '' 's/curruca_nana_28718/PASSERIFORMES_Sylviidae_Curruca_nana/g' $1
sed -i '' 's/dacelo_novaeguineae/CORACIIFORMES_Alcedinidae_Dacelo_novaeguineae/g' $1
sed -i '' 's/daphoenositta_chrysoptera_23086/PASSERIFORMES_Neosittidae_Daphoenositta_chrysoptera/g' $1
sed -i '' 's/dasyornis_broadbenti_22840/PASSERIFORMES_Dasyornithidae_Dasyornis_broadbenti/g' $1
sed -i '' 's/dendrocolaptes_sanctithomae_b8768/PASSERIFORMES_Furnariidae_Dendrocolaptes_sanctithomae/g' $1
sed -i '' 's/devioeca_papuana_18304/PASSERIFORMES_Petroicidae_Devioeca_papuana/g' $1
sed -i '' 's/dicaeum_hypoleucum_20176/PASSERIFORMES_Dicaeidae_Dicaeum_hypoleucum/g' $1
sed -i '' 's/dicrurus_aeneus_23352/PASSERIFORMES_Dicruridae_Dicrurus_aeneus/g' $1
sed -i '' 's/diomedea_nigripes/PROCELLARIIFORMES_Diomedeidae_Phoebastria_nigripes/g' $1
sed -i '' 's/donacobius_atricapilla_1037/PASSERIFORMES_Donacobiidae_Donacobius_atricapilla/g' $1
sed -i '' 's/dromaius_novaehollandiae/CASUARIIFORMES_Casuariidae_Dromaius_novaehollandiae/g' $1
sed -i '' 's/dromas_ardeola/CHARADRIIFORMES_Dromadidae_Dromas_ardeola/g' $1
sed -i '' 's/dryocopus_pileatus/PICIFORMES_Picidae_Dryocopus_pileatus/g' $1
sed -i '' 's/dulus_dominicus_6414/PASSERIFORMES_Dulidae_Dulus_dominicus/g' $1
sed -i '' 's/dyaphorophyia_castanea_29120/PASSERIFORMES_Platysteiridae_Platysteira_castanea/g' $1
sed -i '' 's/edolisoma_tenuirostre_23644/PASSERIFORMES_Campephagidae_Edolisoma_tenuirostre/g' $1
sed -i '' 's/elachura_formosa/PASSERIFORMES_Elachuridae_Elachura_formosa/g' $1
sed -i '' 's/elanoides_forficatus/ACCIPITRIFORMES_Accipitridae_Elanoides_forficatus/g' $1
sed -i '' 's/emberiza_citrinella_b12240/PASSERIFORMES_Emberizidae_Emberiza_citrinella/g' $1
sed -i '' 's/eremophila_alpestris_28950/PASSERIFORMES_Alaudidae_Eremophila_alpestris/g' $1
sed -i '' 's/erpornis_zantholeuca_27942/PASSERIFORMES_Vireonidae_Erpornis_zantholeuca/g' $1
sed -i '' 's/erythrocercus_mccallii_8688/PASSERIFORMES_Erythrocercidae_Erythrocercus_mccallii/g' $1
sed -i '' 's/estrilda_melpoda_19721/PASSERIFORMES_Estrildidae_Estrilda_melpoda/g' $1
sed -i '' 's/eudocimus_albus/PELECANIFORMES_Threskiornithidae_Eudocimus_albus/g' $1
sed -i '' 's/eudromia_elegans/TINAMIFORMES_Tinamidae_Eudromia_elegans/g' $1
sed -i '' 's/eudyptula_minor/SPHENISCIFORMES_Spheniscidae_Eudyptula_minor/g' $1
sed -i '' 's/eulacestoma_nigropectus_12102/PASSERIFORMES_Eulacestomatidae_Eulacestoma_nigropectus/g' $1
sed -i '' 's/eupetes_macrocerus_585232/PASSERIFORMES_Eupetidae_Eupetes_macrocerus/g' $1
sed -i '' 's/eurostopodus_macrotis2/CAPRIMULGIFORMES_Caprimulgidae_Lyncornis_macrotis/g' $1
sed -i '' 's/eurostopodus_mystacalis/CAPRIMULGIFORMES_Caprimulgidae_Eurostopodus_mystacalis/g' $1
sed -i '' 's/eurylaimus_ochromalus_b50329/PASSERIFORMES_Eurylaimidae_Eurylaimus_ochromalus/g' $1
sed -i '' 's/eurypyga_helias/EURYPYGIFORMES_Eurypygidae_Eurypyga_helias/g' $1
sed -i '' 's/falco_mexicanus/FALCONIFORMES_Falconidae_Falco_mexicanus/g' $1
sed -i '' 's/falcunculus_frontatus_57627/PASSERIFORMES_Falcunculidae_Falcunculus_frontatus/g' $1
sed -i '' 's/formicarius_analis_b26904/PASSERIFORMES_Formicariidae_Formicarius_analis/g' $1
sed -i '' 's/foulehaio_carunculatus_26344/PASSERIFORMES_Meliphagidae_Foulehaio_carunculatus/g' $1
sed -i '' 's/fregata_magnificens/SULIFORMES_Fregatidae_Fregata_magnificens/g' $1
sed -i '' 's/fringilla_montifringilla_4293/PASSERIFORMES_Fringillidae_Fringilla_montifringilla/g' $1
sed -i '' 's/furnarius_rufus_11920/PASSERIFORMES_Furnariidae_Furnarius_rufus/g' $1
sed -i '' 's/galbula_albirostris/PICIFORMES_Galbulidae_Galbula_albirostris/g' $1
sed -i '' 's/gallus_gallus/GALLIFORMES_Phasianidae_Gallus_gallus/g' $1
sed -i '' 's/gampsonyx_swainsoni/ACCIPITRIFORMES_Accipitridae_Gampsonyx_swainsonii/g' $1
sed -i '' 's/gavia_immer/GAVIIFORMES_Gaviidae_Gavia_immer/g' $1
sed -i '' 's/gavia_stellata/GAVIIFORMES_Gaviidae_Gavia_stellata/g' $1
sed -i '' 's/gavialis_gangeticus/OUTGROUP_Gavialidae_Gavialis_gangeticus/g' $1
sed -i '' 's/geococcyx_californianus/CUCULIFORMES_Cuculidae_Geococcyx_californianus/g' $1
sed -i '' 's/geotrygon_montana/COLUMBIFORMES_Columbidae_Geotrygon_montana/g' $1
sed -i '' 's/glareola_cinerea/CHARADRIIFORMES_Glareolidae_Glareola_cinerea/g' $1
sed -i '' 's/grallaria_haplonota_b7883/PASSERIFORMES_Grallariidae_Grallaria_haplonota/g' $1
sed -i '' 's/graueria_vittata_385150/PASSERIFORMES_Acrocephalidae_Graueria_vittata/g' $1
sed -i '' 's/grus_canadensis/GRUIFORMES_Gruidae_Antigone_canadensis/g' $1
sed -i '' 's/haematopus_palliatus/CHARADRIIFORMES_Haematopodidae_Haematopus_palliatus/g' $1
sed -i '' 's/harpactes_ardens_26958/TROGONIFORMES_Trogonidae_Harpactes_ardens/g' $1
sed -i '' 's/heliornis_fulica/GRUIFORMES_Heliornithidae_Heliornis_fulica/g' $1
sed -i '' 's/hemiprocne_mystacea/APODIFORMES_Hemiprocnidae_Hemiprocne_mystacea/g' $1
sed -i '' 's/herpetotheres_cachinnans2/FALCONIFORMES_Falconidae_Herpetotheres_cachinnans/g' $1
sed -i '' 's/himantornis_haematopus/GRUIFORMES_Rallidae_Himantornis_haematopus/g' $1
sed -i '' 's/hirundo_rustica_28789/PASSERIFORMES_Hirundinidae_Hirundo_rustica/g' $1
sed -i '' 's/hylia_prasina_29144/PASSERIFORMES_Hyliidae_Hylia_prasina/g' $1
sed -i '' 's/hyliota_flavigaster_439359/PASSERIFORMES_Hyliotidae_Hyliota_flavigaster/g' $1
sed -i '' 's/hylocitrea_bonensis_dot12574/PASSERIFORMES_Hylocitreidae_Hylocitrea_bonensis/g' $1
sed -i '' 's/hypocolius_ampelinus_466652/PASSERIFORMES_Hypocoliidae_Hypocolius_ampelinus/g' $1
sed -i '' 's/hypothymis_azurea_20189/PASSERIFORMES_Monarchidae_Hypothymis_azurea/g' $1
sed -i '' 's/ibidorhyncha_struthersii_776929/CHARADRIIFORMES_Ibidorhynchidae_Ibidorhyncha_struthersii/g' $1
sed -i '' 's/icteria_virens_b60879/PASSERIFORMES_Icteriidae_Icteria_virens/g' $1
sed -i '' 's/icterus_cucullatus_b24601/PASSERIFORMES_Icteridae_Icterus_cucullatus/g' $1
sed -i '' 's/ifrita_kowaldi_12106/PASSERIFORMES_Ifritidae_Ifrita_kowaldi/g' $1
sed -i '' 's/indicator_maculatus/PICIFORMES_Indicatoridae_Indicator_maculatus/g' $1
sed -i '' 's/irena_cyanogastra_25780/PASSERIFORMES_Irenidae_Irena_cyanogastra/g' $1
sed -i '' 's/irena_puella_24448/PASSERIFORMES_Irenidae_Irena_puella/g' $1
sed -i '' 's/jacana_jacana/CHARADRIIFORMES_Jacanidae_Jacana_jacana/g' $1
sed -i '' 's/jynx_ruficollis/PICIFORMES_Picidae_Jynx_ruficollis/g' $1
sed -i '' 's/lamprolia_victoriae_24329/PASSERIFORMES_Rhipiduridae_Lamprolia_victoriae/g' $1
sed -i '' 's/lanius_excubitor_28984/PASSERIFORMES_Laniidae_Lanius_excubitor/g' $1
sed -i '' 's/larus_argentatus_b37399/CHARADRIIFORMES_Laridae_Larus_argentatus/g' $1
sed -i '' 's/leiothrix_lutea_b27032/PASSERIFORMES_Leiothrichidae_Leiothrix_lutea/g' $1
sed -i '' 's/leptocoma_sperata_20350/PASSERIFORMES_Nectariniidae_Leptocoma_sperata/g' $1
sed -i '' 's/leptosomus_discolor/LEPTOSOMIFORMES_Leptosomidae_Leptosomus_discolor/g' $1
sed -i '' 's/loboparadisea_sericea_18403/PASSERIFORMES_Cnemophilidae_Loboparadisea_sericea/g' $1
sed -i '' 's/locustella_lanceolata_4248/PASSERIFORMES_Locustellidae_Locustella_lanceolata/g' $1
sed -i '' 's/lophotis_ruficrista/OTIDIFORMES_Otididae_Lophotis_ruficrista/g' $1
sed -i '' 's/machaerirhynchus_nigripectus_4734/PASSERIFORMES_Machaerirhynchidae_Machaerirhynchus_nigripectus/g' $1
sed -i '' 's/macrosphenus_flavicans_29199/PASSERIFORMES_Macrosphenidae_Macrosphenus_flavicans/g' $1
sed -i '' 's/malacoptila_fusca/PICIFORMES_Bucconidae_Malacoptila_fusca/g' $1
sed -i '' 's/malacorhynchus_membranaceus/ANSERIFORMES_Anatidae_Malacorhynchus_membranaceus/g' $1
sed -i '' 's/malurus_alboscapulatus_16459/PASSERIFORMES_Maluridae_Malurus_alboscapulatus/g' $1
sed -i '' 's/megalaima_virens/PICIFORMES_Megalaimidae_Psilopogon_virens/g' $1
sed -i '' 's/megalurus_palustris_21124/PASSERIFORMES_Locustellidae_Megalurus_palustris/g' $1
sed -i '' 's/megapodius_eremita/GALLIFORMES_Megapodiidae_Megapodius_eremita/g' $1
sed -i '' 's/melampitta_lugubris_16552/PASSERIFORMES_Melampittidae_Melampitta_lugubris/g' $1
sed -i '' 's/melanocharis_versteri_18286/PASSERIFORMES_Melanocharitidae_Melanocharis_versteri/g' $1
sed -i '' 's/melanopareia_maranonica_b14411/PASSERIFORMES_Melanopareiidae_Melanopareia_maranonica/g' $1
sed -i '' 's/meliphaga_montana_12276/PASSERIFORMES_Meliphagidae_Microptilotis_montanus/g' $1
sed -i '' 's/melloria_quoyi_4831/PASSERIFORMES_Artamidae_Melloria_quoyi/g' $1
sed -i '' 's/menura_novaehollandiae_76638/PASSERIFORMES_Menuridae_Menura_novaehollandiae/g' $1
sed -i '' 's/merops_nubicus/CORACIIFORMES_Meropidae_Merops_nubicus/g' $1
sed -i '' 's/mesitornis_unicolor/MESITORNITHIFORMES_Mesitornithidae_Mesitornis_unicolor/g' $1
sed -i '' 's/metabolus_takatsukasae_22596/PASSERIFORMES_Monarchidae_Monarcha_takatsukasae/g' $1
sed -i '' 's/micrastur_semitorquatus/FALCONIFORMES_Falconidae_Micrastur_semitorquatus/g' $1
sed -i '' 's/microhierax_erythrogenys_30969/FALCONIFORMES_Falconidae_Microhierax_erythrogenys/g' $1
sed -i '' 's/microligea_palustris_6294/PASSERIFORMES_Phaenicophilidae_Microligea_palustris/g' $1
sed -i '' 's/micropsitta_finschii/PSITTACIFORMES_Psittaculidae_Micropsitta_finschii/g' $1
sed -i '' 's/mimus_polyglottos_b62704/PASSERIFORMES_Mimidae_Mimus_polyglottos/g' $1
sed -i '' 's/mionectes_striaticollis_b58337/PASSERIFORMES_Tyrannidae_Mionectes_striaticollis/g' $1
sed -i '' 's/mitrospingus_cassinii_b46585/PASSERIFORMES_Mitrospingidae_Mitrospingus_cassinii/g' $1
sed -i '' 's/modulatrix_stictigula_356751/PASSERIFORMES_Modulatricidae_Modulatrix_stictigula/g' $1
sed -i '' 's/moho_nobilis_193377/PASSERIFORMES_Mohoidae_Moho_nobilis/g' $1
sed -i '' 's/mohoua_albicilla_96717/PASSERIFORMES_Mohouidae_Mohoua_albicilla/g' $1
sed -i '' 's/momotus_momota/CORACIIFORMES_Momotidae_Momotus_momota/g' $1
sed -i '' 's/monias_benschi/MESITORNITHIFORMES_Mesitornithidae_Monias_benschi/g' $1
sed -i '' 's/morus_bassanus/SULIFORMES_Sulidae_Morus_bassanus/g' $1
sed -i '' 's/motacilla_alba_10218/PASSERIFORMES_Motacillidae_Motacilla_alba/g' $1
sed -i '' 's/muscicapa_striata_26606/PASSERIFORMES_Muscicapidae_Muscicapa_striata/g' $1
sed -i '' 's/mycteria_americana/CICONIIFORMES_Ciconiidae_Mycteria_americana/g' $1
sed -i '' 's/myiobius_villosus_b11928/PASSERIFORMES_Tityridae_Myiobius_villosus/g' $1
sed -i '' 's/mystacornis_crossleyi_345860/PASSERIFORMES_Vangidae_Mystacornis_crossleyi/g' $1
sed -i '' 's/neomixis_viridis_393344/PASSERIFORMES_Cisticolidae_Neomixis_viridis/g' $1
sed -i '' 's/neopipo_cinnamomea_b42668/PASSERIFORMES_Tyrannidae_Neopipo_cinnamomea/g' $1
sed -i '' 's/nephelomyias_lintoni_b34699/PASSERIFORMES_Tyrannidae_Nephelomyias_lintoni/g' $1
sed -i '' 's/nesillas_typica_356696/PASSERIFORMES_Acrocephalidae_Nesillas_typica/g' $1
sed -i '' 's/nesospingus_speculiferus_346162/PASSERIFORMES_Nesospingidae_Nesospingus_speculiferus/g' $1
sed -i '' 's/nestor_notabilis/PSITTACIFORMES_Strigopidae_Nestor_notabilis/g' $1
sed -i '' 's/nicator_chloris_29190/PASSERIFORMES_Nicatoridae_Nicator_chloris/g' $1
sed -i '' 's/nonnula_ruficapilla/PICIFORMES_Bucconidae_Nonnula_ruficapilla/g' $1
sed -i '' 's/nothocercus_nigrocapillus/TINAMIFORMES_Tinamidae_Nothocercus_nigrocapillus/g' $1
sed -i '' 's/nothoprocta_perdicaria1/TINAMIFORMES_Tinamidae_Nothoprocta_perdicaria/g' $1
sed -i '' 's/notiomystis_cincta_or027795c/PASSERIFORMES_Notiomystidae_Notiomystis_cincta/g' $1
sed -i '' 's/numida_meleagris/GALLIFORMES_Numididae_Numida_meleagris/g' $1
sed -i '' 's/nyctibius_bracteatus/NYCTIBIIFORMES_Nyctibiidae_Phyllaemulor_bracteatus/g' $1
sed -i '' 's/nyctibius_grandis/NYCTIBIIFORMES_Nyctibiidae_Nyctibius_grandis/g' $1
sed -i '' 's/nyctyornis_amicus/CORACIIFORMES_Meropidae_Nyctyornis_amictus/g' $1
sed -i '' 's/oceanites_oceanicus/PROCELLARIIFORMES_Oceanitidae_Oceanites_oceanicus/g' $1
sed -i '' 's/oceanodroma_tethys/PROCELLARIIFORMES_Hydrobatidae_Hydrobates_tethys/g' $1
sed -i '' 's/oedistoma_iliolophus_16163/PASSERIFORMES_Melanocharitidae_Oedistoma_iliolophus/g' $1
sed -i '' 's/onychorhynchus_coronatus_b4194/PASSERIFORMES_Tityridae_Onychorhynchus_coronatus/g' $1
sed -i '' 's/opisthocomus_hoazin/OPISTHOCOMIFORMES_Opisthocomidae_Opisthocomus_hoazin/g' $1
sed -i '' 's/oreocharis_arfaki_16440/PASSERIFORMES_Paramythiidae_Oreocharis_arfaki/g' $1
sed -i '' 's/oreoica_gutturalis_6198/PASSERIFORMES_Oreoicidae_Oreoica_gutturalis/g' $1
sed -i '' 's/oriolus_chinensis_10450/PASSERIFORMES_Oriolidae_Oriolus_chinensis/g' $1
sed -i '' 's/orthonyx_temminckii_76694/PASSERIFORMES_Orthonychidae_Orthonyx_temminckii/g' $1
sed -i '' 's/orthotomus_castaneiceps_25615/PASSERIFORMES_Cisticolidae_Orthotomus_castaneiceps/g' $1
sed -i '' 's/otidiphaps_nobilis/COLUMBIFORMES_Columbidae_Otidiphaps_nobilis/g' $1
sed -i '' 's/oxylabes_madagascariensis_352915/PASSERIFORMES_Bernieridae_Oxylabes_madagascariensis/g' $1
sed -i '' 's/oxyruncus_cristatus_b2080/PASSERIFORMES_Tityridae_Oxyruncus_cristatus/g' $1
sed -i '' 's/oxyura_jamaicensis/ANSERIFORMES_Anatidae_Oxyura_jamaicensis/g' $1
sed -i '' 's/pachycephala_vitiensis_19410/PASSERIFORMES_Pachycephalidae_Pachycephala_vitiensis/g' $1
sed -i '' 's/pandion_haliaetus/ACCIPITRIFORMES_Pandionidae_Pandion_haliaetus/g' $1
sed -i '' 's/panurus_biarmicus_28797/PASSERIFORMES_Panuridae_Panurus_biarmicus/g' $1
sed -i '' 's/paradisaea_minor_16148/PASSERIFORMES_Paradisaeidae_Paradisaea_minor/g' $1
sed -i '' 's/pardalotus_striatus_8886/PASSERIFORMES_Pardalotidae_Pardalotus_striatus/g' $1
sed -i '' 's/parus_major_11167/PASSERIFORMES_Paridae_Parus_major/g' $1
sed -i '' 's/passer_domesticus_28860/PASSERIFORMES_Passeridae_Passer_domesticus/g' $1
sed -i '' 's/passerella_iliaca_b19389/PASSERIFORMES_Passerellidae_Passerella_iliaca/g' $1
sed -i '' 's/pedionomus_torquatus/CHARADRIIFORMES_Pedionomidae_Pedionomus_torquatus/g' $1
sed -i '' 's/pelecanoides_urinatrix/PROCELLARIIFORMES_Procellariidae_Pelecanoides_urinatrix/g' $1
sed -i '' 's/pelecanus_occidentalis/PELECANIFORMES_Pelecanidae_Pelecanus_occidentalis/g' $1
sed -i '' 's/peltops_blainvillii_809112/PASSERIFORMES_Artamidae_Peltops_blainvillii/g' $1
sed -i '' 's/pericrocotus_divaricatus_10261/PASSERIFORMES_Campephagidae_Pericrocotus_divaricatus/g' $1
sed -i '' 's/petroica_multicolor_24355/PASSERIFORMES_Petroicidae_Petroica_multicolor/g' $1
sed -i '' 's/peucedramus_taeniatus_9396/PASSERIFORMES_Peucedramidae_Peucedramus_taeniatus/g' $1
sed -i '' 's/phaenicophaeus_curvirostris1/CUCULIFORMES_Cuculidae_Phaenicophaeus_curvirostris/g' $1
sed -i '' 's/phaenicophilus_palmarum_6310/PASSERIFORMES_Phaenicophilidae_Phaenicophilus_palmarum/g' $1
sed -i '' 's/phaethon_lepturus/PHAETHONTIFORMES_Phaethontidae_Phaethon_lepturus/g' $1
sed -i '' 's/phaethon_rubicauda/PHAETHONTIFORMES_Phaethontidae_Phaethon_rubricauda/g' $1
sed -i '' 's/phalacrocorax_carbo/SULIFORMES_Phalacrocoracidae_Phalacrocorax_carbo/g' $1
sed -i '' 's/pharomachrus_auriceps/TROGONIFORMES_Trogonidae_Pharomachrus_auriceps/g' $1
sed -i '' 's/phegornis_mitchelli/CHARADRIIFORMES_Charadriidae_Phegornis_mitchellii/g' $1
sed -i '' 's/philepitta_castanea_438674/PASSERIFORMES_Philepittidae_Philepitta_castanea/g' $1
sed -i '' 's/philesturnus_carunculatus_14862/PASSERIFORMES_Callaeidae_Philesturnus_carunculatus/g' $1
sed -i '' 's/phodilus_badius/STRIGIFORMES_Tytonidae_Phodilus_badius/g' $1
sed -i '' 's/phoenicopterus_chilensis/PHOENICOPTERIFORMES_Phoenicopteridae_Phoenicopterus_chilensis/g' $1
sed -i '' 's/phoeniculus_purpureus/BUCEROTIFORMES_Phoeniculidae_Phoeniculus_purpureus/g' $1
sed -i '' 's/pholidornis_rushiae_800653/PASSERIFORMES_Hyliidae_Pholidornis_rushiae/g' $1
sed -i '' 's/phonygammus_keraudrenii_12256/PASSERIFORMES_Paradisaeidae_Phonygammus_keraudrenii/g' $1
sed -i '' 's/phylloscopus_trochilus_15495/PASSERIFORMES_Phylloscopidae_Phylloscopus_trochilus/g' $1
sed -i '' 's/picathartes_gymnocephalus_dot2030/PASSERIFORMES_Picathartidae_Picathartes_gymnocephalus/g' $1
sed -i '' 's/pipra_filicauda_b4330/PASSERIFORMES_Pipridae_Pipra_filicauda/g' $1
sed -i '' 's/piprites_chloris_3650/PASSERIFORMES_Tyrannidae_Piprites_chloris/g' $1
sed -i '' 's/pitohui_dichrous_12200/PASSERIFORMES_Oriolidae_Pitohui_dichrous/g' $1
sed -i '' 's/pitta_erythrogaster_15999/PASSERIFORMES_Pittidae_Erythropitta_erythrogaster/g' $1
sed -i '' 's/pitta_guajana/PASSERIFORMES_Pittidae_Hydrornis_guajanus/g' $1
sed -i '' 's/pityriasis_gymnocephala_b50309/PASSERIFORMES_Pityriasidae_Pityriasis_gymnocephala/g' $1
sed -i '' 's/platycercus_elegans/PSITTACIFORMES_Psittaculidae_Platycercus_elegans/g' $1
sed -i '' 's/platylophus_galericulatus_24459/PASSERIFORMES_Platylophidae_Platylophus_galericulatus/g' $1
sed -i '' 's/platyrinchus_saturatus_b20178/PASSERIFORMES_Tyrannidae_Platyrinchus_saturatus/g' $1
sed -i '' 's/ploceus_cucullatus_20062/PASSERIFORMES_Ploceidae_Ploceus_cucullatus/g' $1
sed -i '' 's/pluvianus_aegyptius_b5903/CHARADRIIFORMES_Pluvianidae_Pluvianus_aegyptius/g' $1
sed -i '' 's/pnoepyga_pusilla_15250/PASSERIFORMES_Pnoepygidae_Pnoepyga_pusilla/g' $1
sed -i '' 's/podargus_strigoides2/PODARGIFORMES_Podargidae_Podargus_strigoides/g' $1
sed -i '' 's/podiceps_auritus/PODICIPEDIFORMES_Podicipedidae_Podiceps_auritus/g' $1
sed -i '' 's/poecilotriccus_latirostris_b14792/PASSERIFORMES_Tyrannidae_Poecilotriccus_latirostris/g' $1
sed -i '' 's/pogoniulus_bilineatus/PICIFORMES_Lybiidae_Pogoniulus_bilineatus/g' $1
sed -i '' 's/polioptila_caerulea_b25095/PASSERIFORMES_Polioptilidae_Polioptila_caerulea/g' $1
sed -i '' 's/pomatostomus_superciliosus_8792/PASSERIFORMES_Pomatostomidae_Pomatostomus_superciliosus/g' $1
sed -i '' 's/prionops_plumatus_26690/PASSERIFORMES_Vangidae_Prionops_plumatus/g' $1
sed -i '' 's/prodotiscus_insignis/PICIFORMES_Indicatoridae_Prodotiscus_insignis/g' $1
sed -i '' 's/progne_subis_6623/PASSERIFORMES_Hirundinidae_Progne_subis/g' $1
sed -i '' 's/promerops_gurneyi_70395/PASSERIFORMES_Promeropidae_Promerops_gurneyi/g' $1
sed -i '' 's/prunella_fulvescens_28764/PASSERIFORMES_Prunellidae_Prunella_fulvescens/g' $1
sed -i '' 's/psaltriparus_minimus_22642/PASSERIFORMES_Aegithalidae_Psaltriparus_minimus/g' $1
sed -i '' 's/psittacula_alexandri/PSITTACIFORMES_Psittaculidae_Psittacula_alexandri/g' $1
sed -i '' 's/psittacus_erithacus/PSITTACIFORMES_Psittacidae_Psittacus_erithacus/g' $1
sed -i '' 's/psophia_crepitans/GRUIFORMES_Psophiidae_Psophia_crepitans/g' $1
sed -i '' 's/psophodes_cristatus_6205/PASSERIFORMES_Psophodidae_Psophodes_cristatus/g' $1
sed -i '' 's/pterocles_namaqua/PTEROCLIFORMES_Pteroclidae_Pterocles_namaqua/g' $1
sed -i '' 's/pterocnemia_pennata2/RHEIFORMES_Rheidae_Rhea_pennata/g' $1
sed -i '' 's/pteruthius_aeralatus_17806/PASSERIFORMES_Vireonidae_Pteruthius_aeralatus/g' $1
sed -i '' 's/ptilogonys_caudatus_b16009/PASSERIFORMES_Ptiliogonatidae_Ptiliogonys_caudatus/g' $1
sed -i '' 's/ptilonorhynchus_violaceus_10756/PASSERIFORMES_Ptilonorhynchidae_Ptilonorhynchus_violaceus/g' $1
sed -i '' 's/ptilopachus_petrosus/GALLIFORMES_Odontophoridae_Ptilopachus_petrosus/g' $1
sed -i '' 's/ptilorrhoa_leucosticta_16514/PASSERIFORMES_Cinclosomatidae_Ptilorrhoa_leucosticta/g' $1
sed -i '' 's/puffinus_griseus/PROCELLARIIFORMES_Procellariidae_Ardenna_grisea/g' $1
sed -i '' 's/pycnonotus_jocosus_23591/PASSERIFORMES_Pycnonotidae_Pycnonotus_jocosus/g' $1
sed -i '' 's/pygiptila_stellaris_b42777/PASSERIFORMES_Thamnophilidae_Pygiptila_stellaris/g' $1
sed -i '' 's/pyrrhocorax_pyrrhocorax_28865/PASSERIFORMES_Corvidae_Pyrrhocorax_pyrrhocorax/g' $1
sed -i '' 's/rallus_limicola/GRUIFORMES_Rallidae_Rallus_limicola/g' $1
sed -i '' 's/ramphastos_tucanus_b35545/PICIFORMES_Ramphastidae_Ramphastos_tucanus/g' $1
sed -i '' 's/recurvirostra_americana_b5730/CHARADRIIFORMES_Recurvirostridae_Recurvirostra_americana/g' $1
sed -i '' 's/regulus_calendula_b62760/PASSERIFORMES_Regulidae_Corthylio_calendula/g' $1
sed -i '' 's/regulus_regulus_6778/PASSERIFORMES_Regulidae_Regulus_regulus/g' $1
sed -i '' 's/remiz_consobrinus_28817/PASSERIFORMES_Remizidae_Remiz_consobrinus/g' $1
sed -i '' 's/rhagologus_leucostigma_18382/PASSERIFORMES_Rhagologidae_Rhagologus_leucostigma/g' $1
sed -i '' 's/rhea_americana/RHEIFORMES_Rheidae_Rhea_americana/g' $1
sed -i '' 's/rhinocrypta_lanceolata_b6702/PASSERIFORMES_Rhinocryptidae_Rhinocrypta_lanceolata/g' $1
sed -i '' 's/rhinopomastus_cyanomelas/BUCEROTIFORMES_Phoeniculidae_Rhinopomastus_cyanomelas/g' $1
sed -i '' 's/rhipidura_javanica_17717/PASSERIFORMES_Rhipiduridae_Rhipidura_javanica/g' $1
sed -i '' 's/rhodinocichla_rosea_b26906/PASSERIFORMES_Rhodinocichlidae_Rhodinocichla_rosea/g' $1
sed -i '' 's/rhynochetos_jubatus/EURYPYGIFORMES_Rhynochetidae_Rhynochetos_jubatus/g' $1
sed -i '' 's/robsonius_rabori_25709/PASSERIFORMES_Locustellidae_Robsonius_rabori/g' $1
sed -i '' 's/rollulus_rouloul/GALLIFORMES_Phasianidae_Rollulus_rouloul/g' $1
sed -i '' 's/rostratula_benghalensis/CHARADRIIFORMES_Rostratulidae_Rostratula_benghalensis/g' $1
sed -i '' 's/sagittarius_serpentarius_b2458/ACCIPITRIFORMES_Sagittariidae_Sagittarius_serpentarius/g' $1
sed -i '' 's/salpornis_spilonota_19873/PASSERIFORMES_Certhiidae_Salpornis_spilonota/g' $1
sed -i '' 's/sapayoa_aenigma_b2329/PASSERIFORMES_Sapayoidae_Sapayoa_aenigma/g' $1
sed -i '' 's/sarcoramphus_papa/ACCIPITRIFORMES_Cathartidae_Sarcoramphus_papa/g' $1
sed -i '' 's/sarothrura_elegans/GRUIFORMES_Sarothruridae_Sarothrura_elegans/g' $1
sed -i '' 's/schiffornis_major_b4995/PASSERIFORMES_Tityridae_Schiffornis_major/g' $1
sed -i '' 's/sclerurus_rufigularis_b48483/PASSERIFORMES_Furnariidae_Sclerurus_rufigularis/g' $1
sed -i '' 's/scopus_umbretta/PELECANIFORMES_Scopidae_Scopus_umbretta/g' $1
sed -i '' 's/scotocerca_inquieta_207198/PASSERIFORMES_Scotocercidae_Scotocerca_inquieta/g' $1
sed -i '' 's/seicercus_montis_17754/PASSERIFORMES_Phylloscopidae_Phylloscopus_montis/g' $1
sed -i '' 's/seiurus_aurocapilla_b60642/PASSERIFORMES_Parulidae_Seiurus_aurocapilla/g' $1
sed -i '' 's/semnornis_frantzii_b28234/PICIFORMES_Semnornithidae_Semnornis_frantzii/g' $1
sed -i '' 's/setophaga_magnolia_b5285/PASSERIFORMES_Parulidae_Setophaga_magnolia/g' $1
sed -i '' 's/sitta_europea_30442/PASSERIFORMES_Sittidae_Sitta_europaea/g' $1
sed -i '' 's/smithornis_rufolateralis_15673/PASSERIFORMES_Calyptomenidae_Smithornis_rufolateralis/g' $1
sed -i '' 's/speotyto_cunicularia/STRIGIFORMES_Strigidae_Athene_cunicularia/g' $1
sed -i '' 's/sphyrapicus_varius/PICIFORMES_Picidae_Sphyrapicus_varius/g' $1
sed -i '' 's/spindalis_zena_b11380/PASSERIFORMES_Spindalidae_Spindalis_zena/g' $1
sed -i '' 's/spizella_passerina_b30284/PASSERIFORMES_Passerellidae_Spizella_passerina/g' $1
sed -i '' 's/steatornis_caripensis1/STEATORNITHIFORMES_Steatornithidae_Steatornis_caripensis/g' $1
sed -i '' 's/stercorarius_pomarinus_b20733/CHARADRIIFORMES_Stercorariidae_Stercorarius_pomarinus/g' $1
sed -i '' 's/strepera_graculina_9660/PASSERIFORMES_Artamidae_Strepera_graculina/g' $1
sed -i '' 's/streptoprocne_zonaris2/APODIFORMES_Apodidae_Streptoprocne_zonaris/g' $1
sed -i '' 's/strigops_habroptila_23361/PSITTACIFORMES_Strigopidae_Strigops_habroptila/g' $1
sed -i '' 's/strix_occidentalis/STRIGIFORMES_Strigidae_Strix_occidentalis/g' $1
sed -i '' 's/struthidea_cinerea_10728/PASSERIFORMES_Corcoracidae_Struthidea_cinerea/g' $1
sed -i '' 's/struthio_camelus/STRUTHIONIFORMES_Struthionidae_Struthio_camelus/g' $1
sed -i '' 's/sturnella_neglecta_b37047/PASSERIFORMES_Icteridae_Sturnella_neglecta/g' $1
sed -i '' 's/sturnus_vulgaris_3510/PASSERIFORMES_Sturnidae_Sturnus_vulgaris/g' $1
sed -i '' 's/sula_leucogaster/SULIFORMES_Sulidae_Sula_leucogaster/g' $1
sed -i '' 's/sylvietta_virens_29174/PASSERIFORMES_Macrosphenidae_Sylvietta_virens/g' $1
sed -i '' 's/syrrhaptes_paradoxus/PTEROCLIFORMES_Pteroclidae_Syrrhaptes_paradoxus/g' $1
sed -i '' 's/tachuris_rubrigastra_b49595/PASSERIFORMES_Tyrannidae_Tachuris_rubrigastra/g' $1
sed -i '' 's/tangara_arthus_b58408/PASSERIFORMES_Thraupidae_Tangara_arthus/g' $1
sed -i '' 's/tauraco_erythrolophus/MUSOPHAGIFORMES_Musophagidae_Tauraco_erythrolophus/g' $1
sed -i '' 's/tchagra_senegalus_15518/PASSERIFORMES_Malaconotidae_Tchagra_senegalus/g' $1
sed -i '' 's/tephrodornis_virgatus_30886/PASSERIFORMES_Vangidae_Tephrodornis_virgatus/g' $1
sed -i '' 's/tesia_cyaniventer_27982/PASSERIFORMES_Cettiidae_Tesia_cyaniventer/g' $1
sed -i '' 's/thamnophilus_doliatus_b18845/PASSERIFORMES_Thamnophilidae_Thamnophilus_doliatus/g' $1
sed -i '' 's/thinocorus_orbignyianus2/CHARADRIIFORMES_Thinocoridae_Thinocorus_orbignyianus/g' $1
sed -i '' 's/tichodroma_muraria_61504/PASSERIFORMES_Tichodromidae_Tichodroma_muraria/g' $1
sed -i '' 's/timalia_pileata_23375/PASSERIFORMES_Timaliidae_Timalia_pileata/g' $1
sed -i '' 's/tinamus_guttatus/TINAMIFORMES_Tinamidae_Tinamus_guttatus/g' $1
sed -i '' 's/tityra_cayana_b12385/PASSERIFORMES_Tityridae_Tityra_cayana/g' $1
sed -i '' 's/tockus_camurus/BUCEROTIFORMES_Bucerotidae_Lophoceros_camurus/g' $1
sed -i '' 's/todus_angustirostris/CORACIIFORMES_Todidae_Todus_angustirostris/g' $1
sed -i '' 's/topaza_pella2/APODIFORMES_Trochilidae_Topaza_pella/g' $1
sed -i '' 's/toxorhamphus_novaeguineae_12252/PASSERIFORMES_Melanocharitidae_Toxorhamphus_novaeguineae/g' $1
sed -i '' 's/treron_vernans/COLUMBIFORMES_Columbidae_Treron_vernans/g' $1
sed -i '' 's/trichastoma_pyrrogenys_b36335/PASSERIFORMES_Pellorneidae_Pellorneum_pyrrogenys/g' $1
sed -i '' 's/troglodytes_troglodytes_6774/PASSERIFORMES_Troglodytidae_Troglodytes_troglodytes/g' $1
sed -i '' 's/trogon_personata/TROGONIFORMES_Trogonidae_Trogon_personatus/g' $1
sed -i '' 's/turdus_albicollis_b2555/PASSERIFORMES_Turdidae_Turdus_albicollis/g' $1
sed -i '' 's/turnix_sylvatica/CHARADRIIFORMES_Turnicidae_Turnix_sylvaticus/g' $1
sed -i '' 's/tyrannus_albogularis_b7247/PASSERIFORMES_Tyrannidae_Tyrannus_albogularis/g' $1
sed -i '' 's/tyto_alba/STRIGIFORMES_Tytonidae_Tyto_alba/g' $1
sed -i '' 's/upupa_epops_26612/BUCEROTIFORMES_Upupidae_Upupa_epops/g' $1
sed -i '' 's/urocolius_indicus/COLIIFORMES_Coliidae_Urocolius_indicus/g' $1
sed -i '' 's/urocynchramus_pylzowi_782950/PASSERIFORMES_Urocynchramidae_Urocynchramus_pylzowi/g' $1
sed -i '' 's/vidua_regia_26698/PASSERIFORMES_Viduidae_Vidua_regia/g' $1
sed -i '' 's/vireo_solitarius_25186/PASSERIFORMES_Vireonidae_Vireo_solitarius/g' $1
sed -i '' 's/xanthomixis_zosterops_438702/PASSERIFORMES_Bernieridae_Xanthomixis_zosterops/g' $1
sed -i '' 's/xenicus_gilviventris_or0299521c/PASSERIFORMES_Acanthisittidae_Xenicus_gilviventris/g' $1
sed -i '' 's/xenops_minutus_b12378/PASSERIFORMES_Furnariidae_Xenops_minutus/g' $1
sed -i '' 's/yuhina_everetti_17756/PASSERIFORMES_Zosteropidae_Staphida_everetti/g' $1
sed -i '' 's/zeledonia_coronata_b19768/PASSERIFORMES_Zeledoniidae_Zeledonia_coronata/g' $1
sed -i '' 's/zosterops_everetti_13949/PASSERIFORMES_Zosteropidae_Zosterops_everetti/g' $1
